In [1]:
import numpy as np


In [53]:
X_train = np.array([[0.2, 0.23, 1, 0.4], [0.25, 0.56, 0.3, 0.13], [0.16, 0.18, 0.16, 0.76]]) # try adding more
y_train = np.array([460, 232, 178]) # 
#adding a column for the intercept
X_train=np.c_[np.ones(X_train.shape[0]),X_train]
X_train

array([[1.  , 0.2 , 0.23, 1.  , 0.4 ],
       [1.  , 0.25, 0.56, 0.3 , 0.13],
       [1.  , 0.16, 0.18, 0.16, 0.76]])

###  calculer les valeurs prédit

In [5]:
def outcome_y(x,w):
    
    y_pre=x@w

    return y_pre


### Cost function

In [23]:
def cost_function(x,y, bw):
    
    cost =0
    m=x.shape[0]

    f_wb = outcome_y(x,bw)
    ma_in=((f_wb-y_train)**2)
    cost=sum(ma_in)/(2*m)
    # make the average
    return cost

### calculer le gradient

In [26]:
def compute_gradient(X, y, w):
    
    m=X.shape[0]
    y_pr=outcome_y(X,w)
    dj_b_w=[] 
    d=(y_pr-y).sum()/m
    dj_b_w.append(d)
    X=X[::,1:5]
    d=X.T@(y_pr-y)/m
    dj_b_w.append(d)
                               
    
        
    return dj_b_w

In [41]:
def gradient_descent(X, y,bw_in, alpha, num_iters): 
    # An array to store cost J and w's at each iteration
    J_history = []
    n=X.shape[1]
    #make a copy of w and to avoid modifying global w within function
    w = bw_in[1:n]  
    b = bw_in[0]
    
    for i in range(num_iters):

        # Calculate the gradient and update the parameters
        # compute the gradient
        w=np.insert(w,0,b)

        dj_b_dw = compute_gradient(X, y, w)
        w = w[1:n]  
        b = w[0]
        # Update Parameters using w, b, alpha and gradient
        b= b- alpha*dj_b_dw[0]
        w = w- alpha*dj_b_dw[1]
        J_history.append(w)
        J_history.append(dj_b_dw)
        # Save cost J at each iteration

                      
        
        
        
    return w, b, J_history #return final w,b and J history for graphing

### Regression linéaire

In [14]:
#adding a column for the intercept
x_vec=np.c_[np.ones(X_train.shape[0]),X_train[::,1]]
x_vec

array([[1.  , 0.2 ],
       [1.  , 0.25],
       [1.  , 0.16]])

In [44]:
bw_init = np.zeros(2)


f_wb = outcome_y(x_vec,bw_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

f_wb shape (3,), prediction: [0. 0. 0.]


In [24]:
cost_function(x_vec,y_train, bw_init)

49518.0

In [27]:
#Compute and display gradient 
tmp_dj_d=compute_gradient(x_vec,y_train, bw_init) 
print(f'b at initial w,b:', tmp_dj_d[0])
print(f'w at initial w,b:',  tmp_dj_d[1])

b at initial w,b: -290.0
w at initial w,b: [-59.49333333]


In [46]:
iterations = 100# try ,1000
alpha = 0.0001 #try / 0.00001 / 0.00000001
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(x_vec,y_train,bw_init, alpha, iterations)

print(b_final)
print(w_final)
#m,_ = X_train.shape


0.6171556052156785
[0.59416308]


### Regression multi-linéaire

In [56]:
#adding a column for the intercept
X_train

array([[1.  , 0.2 , 0.23, 1.  , 0.4 ],
       [1.  , 0.25, 0.56, 0.3 , 0.13],
       [1.  , 0.16, 0.18, 0.16, 0.76]])

In [58]:
bw_init = np.zeros(5)


f_wb = outcome_y(X_train,bw_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

f_wb shape (3,), prediction: [0. 0. 0.]


In [59]:
cost_function(X_train,y_train, bw_init)

49518.0

In [60]:
#Compute and display gradient 
tmp_dj_d=compute_gradient(X_train,y_train, bw_init) 
print(f'b at initial w,b:', tmp_dj_d[0])
print(f'w at initial w,b:',  tmp_dj_d[1])

b at initial w,b: -290.0
w at initial w,b: [ -59.49333333  -89.25333333 -186.02666667 -116.48      ]


In [61]:
iterations = 100# try ,1000
alpha = 0.0001 #try / 0.00001 / 0.00000001
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train,y_train,bw_init, alpha, iterations)

print(b_final)
print(w_final)
#m,_ = X_train.shape

0.6153393708955793
[0.59248015 0.88882947 1.85331577 1.15960512]
